name: Build and Push front Docker Image

on:
  workflow_dispatch:
  push:

jobs:
  build-front-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./front/
          push: true
          tags: lerockit/deploy-studies-front-prod
