name: Build and Push API Docker Image

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Dev Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./api/
          push: true
          tags: lerockit/deploy-studies-api-dev

      - name: Push Prod Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./api/
          target: prod
          push: true
          tags: lerockit/deploy-studies-api-prod
